name: CI

on:
  push:
  pull_request:

jobs:
  buildAndTestWindows:

    runs-on:
    - windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.428
    - name: Build & Run Tests
      run: |
        .\build.cmd
    - name: Upload artifact (bin)
      uses: actions/upload-artifact@v4
      with:
        name: bin-windows
        path: bin
    - name: Upload artifact (dist)
      uses: actions/upload-artifact@v4
      with:
        name: dist-windows
        path: dist
        
  buildAndTestLinux:

    runs-on:
    - ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.428
    - name: Build & Run Tests
      run: |
        ./build.sh
    - name: Upload artifact (bin)
      uses: actions/upload-artifact@v4
      with:
        name: bin-linux
        path: bin
    - name: Upload artifact (dist)
      uses: actions/upload-artifact@v4
      with:
        name: dist-linux
        path: dist
        
  buildAndTestMac:

    runs-on:
    - macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.428
    - name: Build & Run Tests
      run: |
        ./build.sh
    - name: Upload artifact (bin)
      uses: actions/upload-artifact@v4
      with:
        name: bin-macos
        path: bin
    - name: Upload artifact (dist)
      uses: actions/upload-artifact@v4
      with:
        name: dist-macos
        path: dist
